import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by openapi-ts (see openapi-ts.config.ts). Regenerated wholesale,
    // never hand-edited, and ships its own `any`s — linting it is pure noise.
    "src/client/**",
  ]),
]);

export default eslintConfig;
