import { client } from "@/src/client/client.gen";

/**
 * One-time configuration for the generated hey-api client.
 *
 * `src/client/` is regenerated by openapi-ts, so nothing in it may be hand-edited —
 * this module holds the two settings the generator cannot know:
 *
 * 1. `credentials: "include"`. Auth is a Django `sessionid` cookie and the API is on
 *    a different origin, so with fetch's `same-origin` default the cookie is never
 *    sent and every call after login returns 401.
 * 2. `baseUrl` from the environment instead of the hardcoded localhost:8000.
 *
 * Import this for its side effect wherever the SDK is used.
 */
/**
 * https, not http: the backend runs under django-sslserver and its sessionid cookie
 * is Secure + SameSite=None, so a plaintext origin can neither connect nor hold it.
 *
 * Exported because `EventSource` is not a hey-api call and cannot read the client's
 * config: `GET /ingest/` returns `stream_url` as a path (`/ingest/<uuid>/stream`), so
 * the SSE consumer has to prefix it itself. That connection also needs its own
 * `{ withCredentials: true }` — `credentials: "include"` below is a fetch option and
 * does not reach it.
 */
export const API_BASE = process.env.NEXT_PUBLIC_API_URL ?? "https://localhost:8000";

client.setConfig({ baseUrl: API_BASE, credentials: "include" });

export { client };

/** HTTP Basic value for POST /core/login/, UTF-8 safe (btoa alone throws on non-Latin1). */
export function basicAuth(username: string, password: string): string {
  const bytes = new TextEncoder().encode(`${username}:${password}`);
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return `Basic ${btoa(binary)}`;
}

/** Strings out of `"a"` / `["a", "b"]` / `{ f: ["a"] }`, which is every leaf DRF produces. */
function messages(value: unknown): string[] {
  if (typeof value === "string") return [value];
  if (Array.isArray(value)) return value.flatMap(messages);
  if (value && typeof value === "object") return Object.values(value).flatMap(messages);
  return [];
}

/**
 * Turn an SDK error into something displayable.
 *
 * The schema advertises three shapes — 401/409 `{msg}` and 418 `{detail: string[]}` — but
 * those are only the ones the backend hand-builds. `base/exceptions.py` also passes DRF and
 * Django validation errors through *raw*, and neither matches:
 *
 *   400  { "config": { "amount_paise": ["Ensure this value is greater than or equal to 1."] } }
 *   409  { "msg": [ ... ] }              // Django's ValidationError.error_list, an array
 *
 * A rule config rejected for being out of range arrives as the first of those, so reading
 * only `typeof msg === "string"` turned every field-level complaint into "Something went
 * wrong" — the merchant is told nothing about the value they just typed. Walk the leaves
 * instead: `msg` and `detail` first because they are the whole message when present, then
 * any field-keyed shape.
 */
export function describeApiError(error: unknown): string {
  if (error && typeof error === "object") {
    const found = messages("msg" in error ? error.msg : "detail" in error ? error.detail : error);
    if (found.length) return found.join(" ");
  }
  return "Something went wrong. Please try again.";
}
